- name: configurar nginx
  hosts: www
  become: True
  roles:
    - nginx
    
- name: desplegar página de bienvenida
  hosts: www
  become: True
  tasks:
    - name: copiar página de bienvenida
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html

- name: configurar mariadb
  hosts: mariadb
  become: True
  tasks:
    - name: installar paquete mariadb
      yum:
        name: "mariadb-server"
        state: present
    - name: arrancar mariadb
      service:
        name: mariadb
        state: started
        enabled: yes
